import "./globals.css";
import type { Metadata } from "next";
import Head from "next/head";
import { Inter } from "next/font/google";
import SideBar from "@/components/SideBar/index";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Foodie Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body className={inter.className}>
        <main className="flex min-h-screen mx-auto">
          <SideBar />
          {children}
        </main>
      </body>
    </html>
  );
}
